#! /usr/bin/python3


choice = int(input("1: Binary to Decimal conversion "+ "\n2: Decimal to Binary conversion\nEnter choice: "))
print("1: Binary to Decimal conversion")
print("2: Decimal to Binary conversion")
bin = ""
if choice ==1:
    numb = int(input("Enter your whole decimal number (integer): "))
    while numb > 1:
        bin = str(numb%2) + bin
        numb = numb // 2
    bin = str(numb%2) + bin
    print(bin)
