#! /usr/bin/python3


#choice = int(input("1: Binary to Decimal conversion "+ "\n2: Decimal to Binary conversion\nEnter choice: "))
print("1: Decimal to Binary")
print("2: Binary to Decimal")
bin = ""
choice=int(input())
if choice ==1:
    numb = int(input("Enter your whole decimal number (integer): "))
    while numb > 1:
        bin = str(numb%2) + bin
        numb = numb // 2
    bin = str(numb%2) + bin
    print(bin)
elif choice ==2:
    total = 0
    numb = (input("Enter your whole binary number: "))
    for i in range (1, (numb.__len__())+1):
        if numb[-i] == str(1):
            total = total + (2**(i-1))
    print(total)
